// texture.cpp
// load and manage textures


// path to the textures - redefined via Makefile
#define TEXTURE_PATH "tex/"

class tex {
	public:
		// list of texture-ids

		// common
		static int FLAMES, SHIELD, HAWHAW, BG_DESERT, BG_SNOW;
		static int MAP_1_PREVIEW, MAP_2_PREVIEW, MAP_3_PREVIEW, MAP_4_PREVIEW;
		static int MAP_5_PREVIEW, MAP_CUSTOM_PREVIEW;
		// ponies
		static int PONY_RARITY, PONY_APPLEJACK, PONY_FLUTTERSHY;
		static int PONY_PINKIE_PIE, PONY_RAINBOW_DASH, PONY_TWILIGHT_SPARKLE;
		static int PONY_TROJAN, PONY_RAINBOW_DASH_FLYING, RAINBOW_DASH_TRAIL;
		static int PONY_SHIELD, PONY_DEAD, BLOOD_DEFAULT, BLOOD_SHIELD;
		// ranks
		static int RANK_1, RANK_2, RANK_3, RANK_4, RANK_5, RANK_6, RANK_7;
		static int RANK_8, RANK_9, RANK_0;
		// menu
		static int MENU_STRATEGY, MENU_UPGRADE, MENU_RECOVER, MENU_REPAIR;
		// tower
		static int TOWER_BASE, TOWER_SHIELD, TOWER_SHIELD_PREVIEW;
		// rifle
		static int TOWER_RIFLE_PREVIEW;
		static int TOWER_RIFLE_3, TOWER_RIFLE_1, TOWER_RIFLE_2;
		static int TOWER_RIFLE_1_FIRE_1, TOWER_RIFLE_1_FIRE_2, TOWER_RIFLE_1_FIRE_3;
		static int TOWER_RIFLE_2_FIRE_1, TOWER_RIFLE_2_FIRE_2, TOWER_RIFLE_2_FIRE_3;
		static int TOWER_RIFLE_3_FIRE_1, TOWER_RIFLE_3_FIRE_2, TOWER_RIFLE_3_FIRE_3;
		// railgun
		static int TOWER_RAILGUN_PREVIEW;
		static int TOWER_RAILGUN_1, TOWER_RAILGUN_2, TOWER_RAILGUN_3;
		static int TOWER_RAILGUN_1_FIRE_1, TOWER_RAILGUN_1_FIRE_2, TOWER_RAILGUN_1_FIRE_3;
		static int TOWER_RAILGUN_1_FIRE_4, TOWER_RAILGUN_1_FIRE_5, TOWER_RAILGUN_1_FIRE_6;
		static int TOWER_RAILGUN_1_FIRE_7, TOWER_RAILGUN_1_FIRE_8, TOWER_RAILGUN_1_FIRE_9;
		static int TOWER_RAILGUN_1_FIRE_10, TOWER_RAILGUN_1_FIRE_11, TOWER_RAILGUN_1_FIRE_12;
		static int TOWER_RAILGUN_1_FIRE_13, TOWER_RAILGUN_1_FIRE_14;
		static int TOWER_RAILGUN_2_FIRE_1, TOWER_RAILGUN_2_FIRE_2, TOWER_RAILGUN_2_FIRE_3;
		static int TOWER_RAILGUN_2_FIRE_4, TOWER_RAILGUN_2_FIRE_5, TOWER_RAILGUN_2_FIRE_6;
		static int TOWER_RAILGUN_2_FIRE_7, TOWER_RAILGUN_2_FIRE_8, TOWER_RAILGUN_2_FIRE_9;
		static int TOWER_RAILGUN_2_FIRE_10, TOWER_RAILGUN_2_FIRE_11, TOWER_RAILGUN_2_FIRE_12;
		static int TOWER_RAILGUN_2_FIRE_13, TOWER_RAILGUN_2_FIRE_14, TOWER_RAILGUN_2_FIRE_15;
		static int TOWER_RAILGUN_3_FIRE_1, TOWER_RAILGUN_3_FIRE_2, TOWER_RAILGUN_3_FIRE_3;
		static int TOWER_RAILGUN_3_FIRE_4, TOWER_RAILGUN_3_FIRE_5, TOWER_RAILGUN_3_FIRE_6;
		static int TOWER_RAILGUN_3_FIRE_7, TOWER_RAILGUN_3_FIRE_8, TOWER_RAILGUN_3_FIRE_9;
		static int TOWER_RAILGUN_3_FIRE_10, TOWER_RAILGUN_3_FIRE_11, TOWER_RAILGUN_3_FIRE_12;
		static int TOWER_RAILGUN_3_FIRE_13, TOWER_RAILGUN_3_FIRE_14, TOWER_RAILGUN_3_FIRE_15;
		// flamethrower
		static int TOWER_FLAMETHROWER_PREVIEW;
		static int TOWER_FLAMETHROWER_1, TOWER_FLAMETHROWER_2, TOWER_FLAMETHROWER_3;
		// laser
		static int TOWER_LASER_PREVIEW;
		static int TOWER_LASER_1, TOWER_LASER_2, TOWER_LASER_3;
		// artillery
		static int TOWER_ARTILLERY_PREVIEW;
		static int TOWER_ARTILLERY_1, TOWER_ARTILLERY_2, TOWER_ARTILLERY_3;
		static int TOWER_ARTILLERY_1_FIRE_1, TOWER_ARTILLERY_1_FIRE_2, TOWER_ARTILLERY_1_FIRE_3;
		static int TOWER_ARTILLERY_1_FIRE_4, TOWER_ARTILLERY_1_FIRE_5, TOWER_ARTILLERY_1_FIRE_6;
		static int TOWER_ARTILLERY_1_FIRE_7, TOWER_ARTILLERY_1_FIRE_8, TOWER_ARTILLERY_1_FIRE_9;
		static int TOWER_ARTILLERY_1_FIRE_10, TOWER_ARTILLERY_1_FIRE_11, TOWER_ARTILLERY_1_FIRE_12;
		static int TOWER_ARTILLERY_1_FIRE_13, TOWER_ARTILLERY_1_FIRE_14, TOWER_ARTILLERY_1_FIRE_15;
		static int TOWER_ARTILLERY_2_FIRE_1, TOWER_ARTILLERY_2_FIRE_2, TOWER_ARTILLERY_2_FIRE_3;
		static int TOWER_ARTILLERY_2_FIRE_4, TOWER_ARTILLERY_2_FIRE_5, TOWER_ARTILLERY_2_FIRE_6;
		static int TOWER_ARTILLERY_2_FIRE_7, TOWER_ARTILLERY_2_FIRE_8, TOWER_ARTILLERY_2_FIRE_9;
		static int TOWER_ARTILLERY_2_FIRE_10, TOWER_ARTILLERY_2_FIRE_11, TOWER_ARTILLERY_2_FIRE_12;
		static int TOWER_ARTILLERY_2_FIRE_13, TOWER_ARTILLERY_2_FIRE_14, TOWER_ARTILLERY_2_FIRE_15;
		static int TOWER_ARTILLERY_3_FIRE_1, TOWER_ARTILLERY_3_FIRE_2, TOWER_ARTILLERY_3_FIRE_3;
		static int TOWER_ARTILLERY_3_FIRE_4, TOWER_ARTILLERY_3_FIRE_5, TOWER_ARTILLERY_3_FIRE_6;
		static int TOWER_ARTILLERY_3_FIRE_7, TOWER_ARTILLERY_3_FIRE_8, TOWER_ARTILLERY_3_FIRE_9;
		static int TOWER_ARTILLERY_3_FIRE_10, TOWER_ARTILLERY_3_FIRE_11, TOWER_ARTILLERY_3_FIRE_12;
		static int TOWER_ARTILLERY_3_FIRE_13, TOWER_ARTILLERY_3_FIRE_14, TOWER_ARTILLERY_3_FIRE_15;
		// support tower
		static int TOWER_FENCE_PREVIEW, TOWER_FENCE, TOWER_FENCE_CORN, TOWER_FENCE_HALF, TOWER_FENCE_JUNCTION;
		static int TOWER_DRONE_PREVIEW, TOWER_DRONE;
		static int TOWER_DRONE_ATTACK_PREVIEW, TOWER_DRONE_ATTACK;

		// load and set textures
		static void init() {

			FLAMES = load("misc/FLAMES");
			SHIELD = load("misc/SHIELD");
			BG_DESERT = load("misc/BG_DESERT");
			BG_SNOW = load("misc/BG_SNOW");
			HAWHAW = load("Applejack/HAWHAW");

			MAP_1_PREVIEW = load("misc/MAP_1_PREVIEW");
			MAP_2_PREVIEW = load("misc/MAP_2_PREVIEW");
			MAP_3_PREVIEW = load("misc/MAP_3_PREVIEW");
			MAP_4_PREVIEW = load("misc/MAP_4_PREVIEW");
			MAP_5_PREVIEW = load("misc/MAP_5_PREVIEW");
			MAP_CUSTOM_PREVIEW = load("misc/MAP_CUSTOM_PREVIEW");

			PONY_RARITY = load("Rarity/PONY_RARITY");
			PONY_APPLEJACK = load("Applejack/PONY_APPLEJACK");
			PONY_FLUTTERSHY = load("Fluttershy/PONY_FLUTTERSHY");
			PONY_PINKIE_PIE = load("PinkiePie/PONY_PINKIE_PIE");
			PONY_RAINBOW_DASH = load("RainbowDash/PONY_RAINBOW_DASH");
			PONY_TWILIGHT_SPARKLE = load("TwilightSparkle/PONY_TWILIGHT_SPARKLE");
			PONY_TROJAN = load("misc/PONY_TROJAN");
			PONY_RAINBOW_DASH_FLYING = load("RainbowDashFlying/PONY_RAINBOW_DASH_FLYING");
			RAINBOW_DASH_TRAIL = load("misc/RAINBOW_DASH_TRAIL");
			PONY_SHIELD = load("misc/PONY_SHIELD");
			PONY_DEAD = load("misc/PONY_DEAD");
			BLOOD_DEFAULT = load("misc/BLOOD_DEFAULT");
			BLOOD_SHIELD = load("misc/BLOOD_SHIELD");

			RANK_0 = load("Derpy/RANK_0");
			RANK_1 = load("Rarity/RANK_1");
			RANK_2 = load("Fluttershy/RANK_2");
			RANK_3 = load("PinkiePie/RANK_3");
			RANK_4 = load("TwilightSparkle/RANK_4");
			RANK_5 = load("RainbowDash/RANK_5");
			RANK_6 = load("RainbowDash/RANK_6");
			RANK_7 = load("Applejack/RANK_7");
			RANK_8 = load("Applejack/RANK_8");
			RANK_9 = load("Applejack/RANK_9");

			MENU_STRATEGY = load("Applejack/MENU_STRATEGY");
			MENU_UPGRADE = load("misc/MENU_UPGRADE");
			MENU_RECOVER = load("misc/MENU_RECOVER");
			MENU_REPAIR = load("misc/MENU_REPAIR");

			TOWER_BASE = load("misc/TOWER_BASE");
			TOWER_SHIELD = load("misc/TOWER_SHIELD");
			TOWER_SHIELD_PREVIEW = load("misc/TOWER_SHIELD_PREVIEW");

			TOWER_RIFLE_PREVIEW = load("misc/TOWER_RIFLE_PREVIEW");
			TOWER_RIFLE_1 = load("misc/TOWER_RIFLE_1");
			TOWER_RIFLE_2 = load("misc/TOWER_RIFLE_2");
			TOWER_RIFLE_3 = load("misc/TOWER_RIFLE_3");
			TOWER_RIFLE_1_FIRE_1 = load("misc/TOWER_RIFLE_1_FIRE_1");
			TOWER_RIFLE_1_FIRE_2 = load("misc/TOWER_RIFLE_1_FIRE_2");
			TOWER_RIFLE_1_FIRE_3 = load("misc/TOWER_RIFLE_1_FIRE_3");
			TOWER_RIFLE_2_FIRE_1 = load("misc/TOWER_RIFLE_2_FIRE_1");
			TOWER_RIFLE_2_FIRE_2 = load("misc/TOWER_RIFLE_2_FIRE_2");
			TOWER_RIFLE_2_FIRE_3 = load("misc/TOWER_RIFLE_2_FIRE_3");
			TOWER_RIFLE_3_FIRE_1 = load("misc/TOWER_RIFLE_3_FIRE_1");
			TOWER_RIFLE_3_FIRE_2 = load("misc/TOWER_RIFLE_3_FIRE_2");
			TOWER_RIFLE_3_FIRE_3 = load("misc/TOWER_RIFLE_3_FIRE_3");

			TOWER_RAILGUN_PREVIEW = load("misc/TOWER_RAILGUN_PREVIEW");
			TOWER_RAILGUN_1 = load("misc/TOWER_RAILGUN_1");
			TOWER_RAILGUN_1_FIRE_1 = load("misc/TOWER_RAILGUN_1_FIRE_1");
			TOWER_RAILGUN_1_FIRE_2 = load("misc/TOWER_RAILGUN_1_FIRE_2");
			TOWER_RAILGUN_1_FIRE_3 = load("misc/TOWER_RAILGUN_1_FIRE_3");
			TOWER_RAILGUN_1_FIRE_4 = load("misc/TOWER_RAILGUN_1_FIRE_4");
			TOWER_RAILGUN_1_FIRE_5 = load("misc/TOWER_RAILGUN_1_FIRE_5");
			TOWER_RAILGUN_1_FIRE_6 = load("misc/TOWER_RAILGUN_1_FIRE_6");
			TOWER_RAILGUN_1_FIRE_7 = load("misc/TOWER_RAILGUN_1_FIRE_7");
			TOWER_RAILGUN_1_FIRE_8 = load("misc/TOWER_RAILGUN_1_FIRE_8");
			TOWER_RAILGUN_1_FIRE_9 = load("misc/TOWER_RAILGUN_1_FIRE_9");
			TOWER_RAILGUN_1_FIRE_10 = load("misc/TOWER_RAILGUN_1_FIRE_10");
			TOWER_RAILGUN_1_FIRE_11 = load("misc/TOWER_RAILGUN_1_FIRE_11");
			TOWER_RAILGUN_1_FIRE_12 = load("misc/TOWER_RAILGUN_1_FIRE_12");
			TOWER_RAILGUN_1_FIRE_13 = load("misc/TOWER_RAILGUN_1_FIRE_13");
			TOWER_RAILGUN_1_FIRE_14 = load("misc/TOWER_RAILGUN_1_FIRE_14");

			TOWER_RAILGUN_2 = load("misc/TOWER_RAILGUN_2");
			TOWER_RAILGUN_2_FIRE_1 = load("misc/TOWER_RAILGUN_2_FIRE_1");
			TOWER_RAILGUN_2_FIRE_2 = load("misc/TOWER_RAILGUN_2_FIRE_2");
			TOWER_RAILGUN_2_FIRE_3 = load("misc/TOWER_RAILGUN_2_FIRE_3");
			TOWER_RAILGUN_2_FIRE_4 = load("misc/TOWER_RAILGUN_2_FIRE_4");
			TOWER_RAILGUN_2_FIRE_5 = load("misc/TOWER_RAILGUN_2_FIRE_5");
			TOWER_RAILGUN_2_FIRE_6 = load("misc/TOWER_RAILGUN_2_FIRE_6");
			TOWER_RAILGUN_2_FIRE_7 = load("misc/TOWER_RAILGUN_2_FIRE_7");
			TOWER_RAILGUN_2_FIRE_8 = load("misc/TOWER_RAILGUN_2_FIRE_8");
			TOWER_RAILGUN_2_FIRE_9 = load("misc/TOWER_RAILGUN_2_FIRE_9");
			TOWER_RAILGUN_2_FIRE_10 = load("misc/TOWER_RAILGUN_2_FIRE_10");
			TOWER_RAILGUN_2_FIRE_11 = load("misc/TOWER_RAILGUN_2_FIRE_11");
			TOWER_RAILGUN_2_FIRE_12 = load("misc/TOWER_RAILGUN_2_FIRE_12");
			TOWER_RAILGUN_2_FIRE_13 = load("misc/TOWER_RAILGUN_2_FIRE_13");
			TOWER_RAILGUN_2_FIRE_14 = load("misc/TOWER_RAILGUN_2_FIRE_14");
			TOWER_RAILGUN_2_FIRE_15 = load("misc/TOWER_RAILGUN_2_FIRE_15");

			TOWER_RAILGUN_3 = load("misc/TOWER_RAILGUN_3");
			TOWER_RAILGUN_3_FIRE_1 = load("misc/TOWER_RAILGUN_3_FIRE_1");
			TOWER_RAILGUN_3_FIRE_2 = load("misc/TOWER_RAILGUN_3_FIRE_2");
			TOWER_RAILGUN_3_FIRE_3 = load("misc/TOWER_RAILGUN_3_FIRE_3");
			TOWER_RAILGUN_3_FIRE_4 = load("misc/TOWER_RAILGUN_3_FIRE_4");
			TOWER_RAILGUN_3_FIRE_5 = load("misc/TOWER_RAILGUN_3_FIRE_5");
			TOWER_RAILGUN_3_FIRE_6 = load("misc/TOWER_RAILGUN_3_FIRE_6");
			TOWER_RAILGUN_3_FIRE_7 = load("misc/TOWER_RAILGUN_3_FIRE_7");
			TOWER_RAILGUN_3_FIRE_8 = load("misc/TOWER_RAILGUN_3_FIRE_8");
			TOWER_RAILGUN_3_FIRE_9 = load("misc/TOWER_RAILGUN_3_FIRE_9");
			TOWER_RAILGUN_3_FIRE_10 = load("misc/TOWER_RAILGUN_3_FIRE_10");
			TOWER_RAILGUN_3_FIRE_11 = load("misc/TOWER_RAILGUN_3_FIRE_11");
			TOWER_RAILGUN_3_FIRE_12 = load("misc/TOWER_RAILGUN_3_FIRE_12");
			TOWER_RAILGUN_3_FIRE_13 = load("misc/TOWER_RAILGUN_3_FIRE_13");
			TOWER_RAILGUN_3_FIRE_14 = load("misc/TOWER_RAILGUN_3_FIRE_14");
			TOWER_RAILGUN_3_FIRE_15 = load("misc/TOWER_RAILGUN_3_FIRE_15");

			TOWER_FLAMETHROWER_PREVIEW = load("misc/TOWER_FLAMETHROWER_PREVIEW");
			TOWER_FLAMETHROWER_1 = load("misc/TOWER_FLAMETHROWER_1");
			TOWER_FLAMETHROWER_2 = load("misc/TOWER_FLAMETHROWER_2");
			TOWER_FLAMETHROWER_3 = load("misc/TOWER_FLAMETHROWER_3");

			TOWER_LASER_PREVIEW = load("misc/TOWER_LASER_PREVIEW");
			TOWER_LASER_1 = load("misc/TOWER_LASER_1");
			TOWER_LASER_2 = load("misc/TOWER_LASER_2");
			TOWER_LASER_3 = load("misc/TOWER_LASER_3");

			TOWER_ARTILLERY_PREVIEW = load("misc/TOWER_ARTILLERY_PREVIEW");
			TOWER_ARTILLERY_1 = load("misc/TOWER_ARTILLERY_1");
			TOWER_ARTILLERY_1_FIRE_1 = load("misc/TOWER_ARTILLERY_1_FIRE_1");
			TOWER_ARTILLERY_1_FIRE_2 = load("misc/TOWER_ARTILLERY_1_FIRE_2");
			TOWER_ARTILLERY_1_FIRE_3 = load("misc/TOWER_ARTILLERY_1_FIRE_3");
			TOWER_ARTILLERY_1_FIRE_4 = load("misc/TOWER_ARTILLERY_1_FIRE_4");
			TOWER_ARTILLERY_1_FIRE_5 = load("misc/TOWER_ARTILLERY_1_FIRE_5");
			TOWER_ARTILLERY_1_FIRE_6 = load("misc/TOWER_ARTILLERY_1_FIRE_6");
			TOWER_ARTILLERY_1_FIRE_7 = load("misc/TOWER_ARTILLERY_1_FIRE_7");
			TOWER_ARTILLERY_1_FIRE_8 = load("misc/TOWER_ARTILLERY_1_FIRE_8");
			TOWER_ARTILLERY_1_FIRE_9 = load("misc/TOWER_ARTILLERY_1_FIRE_9");
			TOWER_ARTILLERY_1_FIRE_10 = load("misc/TOWER_ARTILLERY_1_FIRE_10");
			TOWER_ARTILLERY_1_FIRE_11 = load("misc/TOWER_ARTILLERY_1_FIRE_11");
			TOWER_ARTILLERY_1_FIRE_12 = load("misc/TOWER_ARTILLERY_1_FIRE_12");
			TOWER_ARTILLERY_1_FIRE_13 = load("misc/TOWER_ARTILLERY_1_FIRE_13");
			TOWER_ARTILLERY_1_FIRE_14 = load("misc/TOWER_ARTILLERY_1_FIRE_14");
			TOWER_ARTILLERY_1_FIRE_15 = load("misc/TOWER_ARTILLERY_1_FIRE_15");

			TOWER_ARTILLERY_2 = load("misc/TOWER_ARTILLERY_2");
			TOWER_ARTILLERY_2_FIRE_1 = load("misc/TOWER_ARTILLERY_2_FIRE_1");
			TOWER_ARTILLERY_2_FIRE_2 = load("misc/TOWER_ARTILLERY_2_FIRE_2");
			TOWER_ARTILLERY_2_FIRE_3 = load("misc/TOWER_ARTILLERY_2_FIRE_3");
			TOWER_ARTILLERY_2_FIRE_4 = load("misc/TOWER_ARTILLERY_2_FIRE_4");
			TOWER_ARTILLERY_2_FIRE_5 = load("misc/TOWER_ARTILLERY_2_FIRE_5");
			TOWER_ARTILLERY_2_FIRE_6 = load("misc/TOWER_ARTILLERY_2_FIRE_6");
			TOWER_ARTILLERY_2_FIRE_7 = load("misc/TOWER_ARTILLERY_2_FIRE_7");
			TOWER_ARTILLERY_2_FIRE_8 = load("misc/TOWER_ARTILLERY_2_FIRE_8");
			TOWER_ARTILLERY_2_FIRE_9 = load("misc/TOWER_ARTILLERY_2_FIRE_9");
			TOWER_ARTILLERY_2_FIRE_10 = load("misc/TOWER_ARTILLERY_2_FIRE_10");
			TOWER_ARTILLERY_2_FIRE_11 = load("misc/TOWER_ARTILLERY_2_FIRE_11");
			TOWER_ARTILLERY_2_FIRE_12 = load("misc/TOWER_ARTILLERY_2_FIRE_12");
			TOWER_ARTILLERY_2_FIRE_13 = load("misc/TOWER_ARTILLERY_2_FIRE_13");
			TOWER_ARTILLERY_2_FIRE_14 = load("misc/TOWER_ARTILLERY_2_FIRE_14");
			TOWER_ARTILLERY_2_FIRE_15 = load("misc/TOWER_ARTILLERY_2_FIRE_15");

			TOWER_ARTILLERY_3 = load("misc/TOWER_ARTILLERY_3");
			TOWER_ARTILLERY_3_FIRE_1 = load("misc/TOWER_ARTILLERY_3_FIRE_1");
			TOWER_ARTILLERY_3_FIRE_2 = load("misc/TOWER_ARTILLERY_3_FIRE_2");
			TOWER_ARTILLERY_3_FIRE_3 = load("misc/TOWER_ARTILLERY_3_FIRE_3");
			TOWER_ARTILLERY_3_FIRE_4 = load("misc/TOWER_ARTILLERY_3_FIRE_4");
			TOWER_ARTILLERY_3_FIRE_5 = load("misc/TOWER_ARTILLERY_3_FIRE_5");
			TOWER_ARTILLERY_3_FIRE_6 = load("misc/TOWER_ARTILLERY_3_FIRE_6");
			TOWER_ARTILLERY_3_FIRE_7 = load("misc/TOWER_ARTILLERY_3_FIRE_7");
			TOWER_ARTILLERY_3_FIRE_8 = load("misc/TOWER_ARTILLERY_3_FIRE_8");
			TOWER_ARTILLERY_3_FIRE_9 = load("misc/TOWER_ARTILLERY_3_FIRE_9");
			TOWER_ARTILLERY_3_FIRE_10 = load("misc/TOWER_ARTILLERY_3_FIRE_10");
			TOWER_ARTILLERY_3_FIRE_11 = load("misc/TOWER_ARTILLERY_3_FIRE_11");
			TOWER_ARTILLERY_3_FIRE_12 = load("misc/TOWER_ARTILLERY_3_FIRE_12");
			TOWER_ARTILLERY_3_FIRE_13 = load("misc/TOWER_ARTILLERY_3_FIRE_13");
			TOWER_ARTILLERY_3_FIRE_14 = load("misc/TOWER_ARTILLERY_3_FIRE_14");
			TOWER_ARTILLERY_3_FIRE_15 = load("misc/TOWER_ARTILLERY_3_FIRE_15");

			TOWER_FENCE = load("misc/TOWER_FENCE");
			TOWER_FENCE_CORN = load("misc/TOWER_FENCE_CORN");
			TOWER_FENCE_HALF = load("misc/TOWER_FENCE_HALF");
			TOWER_FENCE_JUNCTION = load("misc/TOWER_FENCE_JUNCTION");
			TOWER_FENCE_PREVIEW = load("Rarity/TOWER_FENCE_PREVIEW");
			TOWER_DRONE = load("misc/TOWER_DRONE");
			TOWER_DRONE_PREVIEW = load("misc/TOWER_DRONE_PREVIEW");
			TOWER_DRONE_ATTACK = load("misc/TOWER_DRONE_ATTACK");
			TOWER_DRONE_ATTACK_PREVIEW = load("misc/TOWER_DRONE_ATTACK_PREVIEW");

		}

	private:
		// function to load a texture
		static int load(const char *path) {
			char buffer[512] = {0};
			strncat(buffer, TEXTURE_PATH, 511);
			strncat(buffer, path, 511);
			strncat(buffer, ".png", 511);

			int id = SOIL_load_OGL_texture(buffer, SOIL_LOAD_AUTO, SOIL_CREATE_NEW_ID, SOIL_FLAG_INVERT_Y);
			if(id == 0) {
				fprintf(stderr, "Error: can't load texture:\n%s\n", buffer);
				exit(1);
			}
			return id;
		}
};


// static definitions (tex class)
int tex::FLAMES = 0, tex::SHIELD = 0, tex::HAWHAW = 0;
int tex::BG_DESERT = 0, tex::BG_SNOW = 0;

int tex::MAP_1_PREVIEW = 0, tex::MAP_2_PREVIEW = 0;
int tex::MAP_3_PREVIEW = 0, tex::MAP_4_PREVIEW = 0;
int tex::MAP_5_PREVIEW = 0, tex::MAP_CUSTOM_PREVIEW = 0;

int tex::PONY_RARITY = 0;
int tex::PONY_APPLEJACK = 0;
int tex::PONY_FLUTTERSHY = 0;
int tex::PONY_PINKIE_PIE = 0;
int tex::PONY_RAINBOW_DASH = 0;
int tex::PONY_TWILIGHT_SPARKLE = 0;
int tex::PONY_TROJAN = 0;
int tex::PONY_RAINBOW_DASH_FLYING = 0;
int tex::RAINBOW_DASH_TRAIL = 0;
int tex::PONY_SHIELD = 0;
int tex::PONY_DEAD = 0;
int tex::BLOOD_DEFAULT = 0;
int tex::BLOOD_SHIELD = 0;

int tex::RANK_0 = 0, tex::RANK_1 = 0, tex::RANK_2 = 0;
int tex::RANK_3 = 0, tex::RANK_4 = 0, tex::RANK_5 = 0;
int tex::RANK_6 = 0, tex::RANK_7 = 0, tex::RANK_8 = 0;
int tex::RANK_9 = 0;

int tex::MENU_STRATEGY = 0, tex::MENU_UPGRADE = 0;
int tex::MENU_RECOVER = 0, tex::MENU_REPAIR = 0;

int tex::TOWER_BASE = 0, tex::TOWER_SHIELD = 0, tex::TOWER_SHIELD_PREVIEW = 0;

int tex::TOWER_RIFLE_PREVIEW = 0;
int tex::TOWER_RIFLE_1 = 0;
int tex::TOWER_RIFLE_2 = 0;
int tex::TOWER_RIFLE_3 = 0;
int tex::TOWER_RIFLE_1_FIRE_1 = 0;
int tex::TOWER_RIFLE_1_FIRE_2 = 0;
int tex::TOWER_RIFLE_1_FIRE_3 = 0;
int tex::TOWER_RIFLE_2_FIRE_1 = 0;
int tex::TOWER_RIFLE_2_FIRE_2 = 0;
int tex::TOWER_RIFLE_2_FIRE_3 = 0;
int tex::TOWER_RIFLE_3_FIRE_1 = 0;
int tex::TOWER_RIFLE_3_FIRE_2 = 0;
int tex::TOWER_RIFLE_3_FIRE_3 = 0;

int tex::TOWER_RAILGUN_PREVIEW = 0;

int tex::TOWER_RAILGUN_1 = 0;
int tex::TOWER_RAILGUN_1_FIRE_1 = 0;
int tex::TOWER_RAILGUN_1_FIRE_2 = 0;
int tex::TOWER_RAILGUN_1_FIRE_3 = 0;
int tex::TOWER_RAILGUN_1_FIRE_4 = 0;
int tex::TOWER_RAILGUN_1_FIRE_5 = 0;
int tex::TOWER_RAILGUN_1_FIRE_6 = 0;
int tex::TOWER_RAILGUN_1_FIRE_7 = 0;
int tex::TOWER_RAILGUN_1_FIRE_8 = 0;
int tex::TOWER_RAILGUN_1_FIRE_9 = 0;
int tex::TOWER_RAILGUN_1_FIRE_10 = 0;
int tex::TOWER_RAILGUN_1_FIRE_11 = 0;
int tex::TOWER_RAILGUN_1_FIRE_12 = 0;
int tex::TOWER_RAILGUN_1_FIRE_13 = 0;
int tex::TOWER_RAILGUN_1_FIRE_14 = 0;

int tex::TOWER_RAILGUN_2 = 0;
int tex::TOWER_RAILGUN_2_FIRE_1 = 0;
int tex::TOWER_RAILGUN_2_FIRE_2 = 0;
int tex::TOWER_RAILGUN_2_FIRE_3 = 0;
int tex::TOWER_RAILGUN_2_FIRE_4 = 0;
int tex::TOWER_RAILGUN_2_FIRE_5 = 0;
int tex::TOWER_RAILGUN_2_FIRE_6 = 0;
int tex::TOWER_RAILGUN_2_FIRE_7 = 0;
int tex::TOWER_RAILGUN_2_FIRE_8 = 0;
int tex::TOWER_RAILGUN_2_FIRE_9 = 0;
int tex::TOWER_RAILGUN_2_FIRE_10 = 0;
int tex::TOWER_RAILGUN_2_FIRE_11 = 0;
int tex::TOWER_RAILGUN_2_FIRE_12 = 0;
int tex::TOWER_RAILGUN_2_FIRE_13 = 0;
int tex::TOWER_RAILGUN_2_FIRE_14 = 0;
int tex::TOWER_RAILGUN_2_FIRE_15 = 0;

int tex::TOWER_RAILGUN_3 = 0;
int tex::TOWER_RAILGUN_3_FIRE_1 = 0;
int tex::TOWER_RAILGUN_3_FIRE_2 = 0;
int tex::TOWER_RAILGUN_3_FIRE_3 = 0;
int tex::TOWER_RAILGUN_3_FIRE_4 = 0;
int tex::TOWER_RAILGUN_3_FIRE_5 = 0;
int tex::TOWER_RAILGUN_3_FIRE_6 = 0;
int tex::TOWER_RAILGUN_3_FIRE_7 = 0;
int tex::TOWER_RAILGUN_3_FIRE_8 = 0;
int tex::TOWER_RAILGUN_3_FIRE_9 = 0;
int tex::TOWER_RAILGUN_3_FIRE_10 = 0;
int tex::TOWER_RAILGUN_3_FIRE_11 = 0;
int tex::TOWER_RAILGUN_3_FIRE_12 = 0;
int tex::TOWER_RAILGUN_3_FIRE_13 = 0;
int tex::TOWER_RAILGUN_3_FIRE_14 = 0;
int tex::TOWER_RAILGUN_3_FIRE_15 = 0;

int tex::TOWER_FLAMETHROWER_PREVIEW = 0;
int tex::TOWER_FLAMETHROWER_1 = 0;
int tex::TOWER_FLAMETHROWER_2 = 0;
int tex::TOWER_FLAMETHROWER_3 = 0;

int tex::TOWER_LASER_PREVIEW = 0;
int tex::TOWER_LASER_1 = 0;
int tex::TOWER_LASER_2 = 0;
int tex::TOWER_LASER_3 = 0;

int tex::TOWER_ARTILLERY_PREVIEW = 0;
int tex::TOWER_ARTILLERY_1 = 0;
int tex::TOWER_ARTILLERY_1_FIRE_1 = 0;
int tex::TOWER_ARTILLERY_1_FIRE_2 = 0;
int tex::TOWER_ARTILLERY_1_FIRE_3 = 0;
int tex::TOWER_ARTILLERY_1_FIRE_4 = 0;
int tex::TOWER_ARTILLERY_1_FIRE_5 = 0;
int tex::TOWER_ARTILLERY_1_FIRE_6 = 0;
int tex::TOWER_ARTILLERY_1_FIRE_7 = 0;
int tex::TOWER_ARTILLERY_1_FIRE_8 = 0;
int tex::TOWER_ARTILLERY_1_FIRE_9 = 0;
int tex::TOWER_ARTILLERY_1_FIRE_10 = 0;
int tex::TOWER_ARTILLERY_1_FIRE_11 = 0;
int tex::TOWER_ARTILLERY_1_FIRE_12 = 0;
int tex::TOWER_ARTILLERY_1_FIRE_13 = 0;
int tex::TOWER_ARTILLERY_1_FIRE_14 = 0;
int tex::TOWER_ARTILLERY_1_FIRE_15 = 0;

int tex::TOWER_ARTILLERY_2 = 0;
int tex::TOWER_ARTILLERY_2_FIRE_1 = 0;
int tex::TOWER_ARTILLERY_2_FIRE_2 = 0;
int tex::TOWER_ARTILLERY_2_FIRE_3 = 0;
int tex::TOWER_ARTILLERY_2_FIRE_4 = 0;
int tex::TOWER_ARTILLERY_2_FIRE_5 = 0;
int tex::TOWER_ARTILLERY_2_FIRE_6 = 0;
int tex::TOWER_ARTILLERY_2_FIRE_7 = 0;
int tex::TOWER_ARTILLERY_2_FIRE_8 = 0;
int tex::TOWER_ARTILLERY_2_FIRE_9 = 0;
int tex::TOWER_ARTILLERY_2_FIRE_10 = 0;
int tex::TOWER_ARTILLERY_2_FIRE_11 = 0;
int tex::TOWER_ARTILLERY_2_FIRE_12 = 0;
int tex::TOWER_ARTILLERY_2_FIRE_13 = 0;
int tex::TOWER_ARTILLERY_2_FIRE_14 = 0;
int tex::TOWER_ARTILLERY_2_FIRE_15 = 0;

int tex::TOWER_ARTILLERY_3 = 0;
int tex::TOWER_ARTILLERY_3_FIRE_1 = 0;
int tex::TOWER_ARTILLERY_3_FIRE_2 = 0;
int tex::TOWER_ARTILLERY_3_FIRE_3 = 0;
int tex::TOWER_ARTILLERY_3_FIRE_4 = 0;
int tex::TOWER_ARTILLERY_3_FIRE_5 = 0;
int tex::TOWER_ARTILLERY_3_FIRE_6 = 0;
int tex::TOWER_ARTILLERY_3_FIRE_7 = 0;
int tex::TOWER_ARTILLERY_3_FIRE_8 = 0;
int tex::TOWER_ARTILLERY_3_FIRE_9 = 0;
int tex::TOWER_ARTILLERY_3_FIRE_10 = 0;
int tex::TOWER_ARTILLERY_3_FIRE_11 = 0;
int tex::TOWER_ARTILLERY_3_FIRE_12 = 0;
int tex::TOWER_ARTILLERY_3_FIRE_13 = 0;
int tex::TOWER_ARTILLERY_3_FIRE_14 = 0;
int tex::TOWER_ARTILLERY_3_FIRE_15 = 0;

int tex::TOWER_FENCE = 0;
int tex::TOWER_FENCE_CORN = 0;
int tex::TOWER_FENCE_HALF = 0;
int tex::TOWER_FENCE_JUNCTION = 0;
int tex::TOWER_FENCE_PREVIEW = 0;
int tex::TOWER_DRONE = 0;
int tex::TOWER_DRONE_PREVIEW = 0;
int tex::TOWER_DRONE_ATTACK = 0;
int tex::TOWER_DRONE_ATTACK_PREVIEW = 0;
